services:
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./notes.json:/app/notes.json

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
    restart: unless-stopped