name: Test, Build and Push

on:
  push:
    branches-ignore:
      - main

jobs:
  build_image_and_push_to_docker_hub:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4

      # ---------- Lint stage ----------
      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install backend dependencies
        working-directory: backend
        run: npm ci

      - name: run eslint (backend)
        working-directory: backend
        run: npm run lint

      - name: install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: run eslint (frontend)
        working-directory: frontend
        run: npm run lint

      # ---------- Build & push ----------
      - name: log in to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push backend to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ${{ vars.BACKEND_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push frontend to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: ${{ vars.FRONTEND_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max