name: Full CI + CD Pipeline

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit